name: Release

on:
  push:
    branches:
      - master
env:
  DOCKER_HUB_USER: whitewaterguide
  DOCKER_HUB_IMAGE: synapse
  GITHUB_USER: ww-github
  REGISTRY: ghcr.io

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GITHUB_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic release
        id: semantic # Need an `id` for output variables
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        if: steps.semantic.outputs.new_release_published == 'true'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.semantic.outputs.new_release_version }}
            ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_IMAGE }}:latest
            ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_IMAGE }}:${{ steps.semantic.outputs.new_release_version }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
